import turtle
ana = turtle.Pen()
ana.shape("turtle")
ana.color("cyan")
ana.width(5)
ana.speed(5)
for i in range(4):
    ana.forward(100)
    ana.left(90)
ana.reset()
ana.color("cyan")
ana.width(5)
ana.speed(0)
for i in range(8):
    ana.forward(200)
    ana.left(225)
ana.reset()
ana.color("cyan")
ana.width(5)
ana.speed(5)
for i in range(20):
    ana.forward(10 * i)
    ana.left(90)
ana.reset()
ana.color("cyan")
ana.width(5)
ana.speed(0)
for i in range(100):
    ana.circle(i * 3)
    ana.left(10)
ana.reset()
ana.color("cyan")
ana.width(5)
ana.speed(0)
for i in range(50):
    ana.circle(i * 3, 180)
    ana.right(45)
ana.reset()
ana.color("cyan")
ana.width(5)
ana.speed(0)
for i in range(100):
    ana.forward(i * 2)
    ana.circle(i * 2, 90) 
    ana.right(20)
ana.reset()
ana.color("cyan")
ana.width(5)
ana.speed(0)
for i in range(50):
    ana.circle(i * 10, 10)
    ana.forward(100)
    ana.right(90) 
ana.reset()
ana.color("cyan")
ana.width(5)
ana.speed(0)
for i in range(50):
    ana.circle(i * 10, 50)
    ana.forward(100)
    ana.right(10000) 